
setname:
  DUMMY: 100
  DUMMY2: 200
  DUMMY04: 40
  DUMMY07: 70
order: ['DUMMY04', 'DUMMY07', 'DUMMY', 'DUMMY2']
average_data : ['objvalue']
convert_to_float: ['objvalue', 'usedlinksrate']
columname: setname