data_file: ./data/edited/edited.csv
replace:
  DUMMY: 100
  DUMMY2: 200
  DUMMY04: 40
  DUMMY07: 70
order: [DUMMY04, DUMMY07, DUMMY, DUMMY2]
solver: [ILP_GUROBI, QL_DUMMY, GREEDY]
labels: [ILP-SE, QL-SE, Greedy-SE]
plot_configs:
  - y_name: Acceptance rate
    data: objvalue
    filename: objvalue_comparison
    ylim_top: 1.05
    runtime : False
  - y_name: Run time
    data: runtime
    filename: runtime_comparison
    runtime : True
  - y_name: Used links per slices
    data: usedlinksrate
    filename: usedlinkscount_comparison
    ylim_top: 15
    runtime : False
